{"name": "Проверка получения ошибки при повторном использовании логина для создания курьера", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <tests.test_courier_create.TestCourierCreate object at 0x000002586B859E20>\n\n    @allure.title('Проверка получения ошибки при повторном использовании логина для создания курьера')\n    @allure.description('Проверяются код и тело ответа.')\n    def test_create_courier_account_login_conflict(self):\n        payload = {\n            'login': Data.valid_login,\n            'password': create_random_password(),\n            'firstName': create_random_firstname()\n        }\n        response = requests.post(Urls.URL_courier_create, data=payload)\n        assert response.status_code == 409\n>       assert response.json().get('message') == 'Этот логин уже используется'\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_courier_create.py:35: AssertionError"}, "description": "Проверяются код и тело ответа.", "start": 1723036924044, "stop": 1723036924295, "uuid": "1e63aadb-a63e-40ae-97c9-9195f187808d", "historyId": "714bc3b37d8bc5a0b1a0a11553321429", "testCaseId": "714bc3b37d8bc5a0b1a0a11553321429", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_account_login_conflict", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-82VEM3U"}, {"name": "thread", "value": "12784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}